/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author Bernardo
 */
public class WelcomeMenu extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeMenu
     */
    public WelcomeMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelLeiloes = new javax.swing.JPanel();
        jButtonShowMenuLeiloes = new javax.swing.JButton();
        jPanelProcessosIndividuais = new javax.swing.JPanel();
        jButtonShowMenuPI = new javax.swing.JButton();
        jPanelProcessosEmpresas = new javax.swing.JPanel();
        jButtonShowMenuPE = new javax.swing.JButton();
        jPanelMenuPE = new javax.swing.JPanel();
        jButtonListarPE = new javax.swing.JButton();
        jButtonRegistarPE = new javax.swing.JButton();
        jPanelMenuPI = new javax.swing.JPanel();
        jButtonListarPI = new javax.swing.JButton();
        jButtonRegistarPI = new javax.swing.JButton();
        jPanelMenuLeiloes = new javax.swing.JPanel();
        jButtonListarLeiloes = new javax.swing.JButton();
        jButtonRegistarLeiloes = new javax.swing.JButton();
        jPanelBackground = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lex-Guima");
        setPreferredSize(new java.awt.Dimension(620, 385));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelPrincipal.setLayout(null);

        jPanelLeiloes.setLayout(null);

        jButtonShowMenuLeiloes.setText("Leilões");
        jButtonShowMenuLeiloes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowMenuLeiloesActionPerformed(evt);
            }
        });
        jPanelLeiloes.add(jButtonShowMenuLeiloes);
        jButtonShowMenuLeiloes.setBounds(0, 0, 120, 110);

        jPanelPrincipal.add(jPanelLeiloes);
        jPanelLeiloes.setBounds(0, 220, 120, 110);

        jPanelProcessosIndividuais.setLayout(null);

        jButtonShowMenuPI.setText("<html> Processos <br> Individuais </html>");
        jButtonShowMenuPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowMenuPIActionPerformed(evt);
            }
        });
        jPanelProcessosIndividuais.add(jButtonShowMenuPI);
        jButtonShowMenuPI.setBounds(0, 0, 120, 110);

        jPanelPrincipal.add(jPanelProcessosIndividuais);
        jPanelProcessosIndividuais.setBounds(0, 110, 120, 110);

        jPanelProcessosEmpresas.setLayout(null);

        jButtonShowMenuPE.setText("<html> Processos de <br> Empresas </html>");
        jButtonShowMenuPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowMenuPEActionPerformed(evt);
            }
        });
        jPanelProcessosEmpresas.add(jButtonShowMenuPE);
        jButtonShowMenuPE.setBounds(0, 0, 119, 110);

        jPanelPrincipal.add(jPanelProcessosEmpresas);
        jPanelProcessosEmpresas.setBounds(0, 0, 120, 110);

        jPanelMenuPE.setLayout(null);

        jButtonListarPE.setText("Listar");
        jButtonListarPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPEActionPerformed(evt);
            }
        });
        jPanelMenuPE.add(jButtonListarPE);
        jButtonListarPE.setBounds(20, 20, 80, 23);

        jButtonRegistarPE.setText("Registar");
        jButtonRegistarPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarPEActionPerformed(evt);
            }
        });
        jPanelMenuPE.add(jButtonRegistarPE);
        jButtonRegistarPE.setBounds(20, 60, 80, 23);

        jPanelPrincipal.add(jPanelMenuPE);
        jPanelMenuPE.setBounds(0, 0, 120, 110);

        jPanelMenuPI.setLayout(null);

        jButtonListarPI.setText("Listar");
        jPanelMenuPI.add(jButtonListarPI);
        jButtonListarPI.setBounds(20, 20, 80, 23);

        jButtonRegistarPI.setText("Registar");
        jPanelMenuPI.add(jButtonRegistarPI);
        jButtonRegistarPI.setBounds(20, 60, 80, 23);

        jPanelPrincipal.add(jPanelMenuPI);
        jPanelMenuPI.setBounds(0, 110, 120, 110);

        jButtonListarLeiloes.setText("Listar");

        jButtonRegistarLeiloes.setText("Registar");

        javax.swing.GroupLayout jPanelMenuLeiloesLayout = new javax.swing.GroupLayout(jPanelMenuLeiloes);
        jPanelMenuLeiloes.setLayout(jPanelMenuLeiloesLayout);
        jPanelMenuLeiloesLayout.setHorizontalGroup(
            jPanelMenuLeiloesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLeiloesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelMenuLeiloesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegistarLeiloes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListarLeiloes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelMenuLeiloesLayout.setVerticalGroup(
            jPanelMenuLeiloesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLeiloesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonListarLeiloes)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistarLeiloes)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelMenuLeiloes);
        jPanelMenuLeiloes.setBounds(0, 220, 120, 110);

        jPanelBackground.setLayout(null);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/scales_full-300x300.jpg"))); // NOI18N
        jPanelBackground.add(jLabelBackground);
        jLabelBackground.setBounds(4, 4, 690, 320);

        jPanelPrincipal.add(jPanelBackground);
        jPanelBackground.setBounds(120, 0, 710, 330);

        getContentPane().add(jPanelPrincipal);
        jPanelPrincipal.setBounds(0, 0, 700, 340);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowMenuLeiloesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowMenuLeiloesActionPerformed
        jPanelLeiloes.setVisible(false);
        jPanelProcessosEmpresas.setVisible(true);
        jPanelProcessosIndividuais.setVisible(true);
    }//GEN-LAST:event_jButtonShowMenuLeiloesActionPerformed

    private void jButtonShowMenuPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowMenuPEActionPerformed
        jPanelProcessosEmpresas.setVisible(false);
        jPanelProcessosIndividuais.setVisible(true);
        jPanelLeiloes.setVisible(true);
    }//GEN-LAST:event_jButtonShowMenuPEActionPerformed

    private void jButtonListarPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListarPEActionPerformed

    private void jButtonRegistarPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarPEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistarPEActionPerformed

    private void jButtonShowMenuPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowMenuPIActionPerformed
        jPanelProcessosEmpresas.setVisible(true);
        jPanelProcessosIndividuais.setVisible(false);
        jPanelLeiloes.setVisible(true);
        
    }//GEN-LAST:event_jButtonShowMenuPIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListarLeiloes;
    private javax.swing.JButton jButtonListarPE;
    private javax.swing.JButton jButtonListarPI;
    private javax.swing.JButton jButtonRegistarLeiloes;
    private javax.swing.JButton jButtonRegistarPE;
    private javax.swing.JButton jButtonRegistarPI;
    private javax.swing.JButton jButtonShowMenuLeiloes;
    private javax.swing.JButton jButtonShowMenuPE;
    private javax.swing.JButton jButtonShowMenuPI;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelLeiloes;
    private javax.swing.JPanel jPanelMenuLeiloes;
    private javax.swing.JPanel jPanelMenuPE;
    private javax.swing.JPanel jPanelMenuPI;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelProcessosEmpresas;
    private javax.swing.JPanel jPanelProcessosIndividuais;
    // End of variables declaration//GEN-END:variables
}
